spring:
  datasource:
    username: root
    password: root@123
    url: jdbc:mysql://localhost:3306/sms
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  # mvc:
  #   view:
  #     suffix: .html
  # thymeleaf:
  #   prefix: /templates/

